pid /tmp/nginx.pid;
error_log /dev/stderr warn;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout;

  client_body_temp_path /tmp/client_temp;
  proxy_temp_path /tmp/proxy_temp;
  fastcgi_temp_path /tmp/fastcgi_temp;
  uwsgi_temp_path /tmp/uwsgi_temp;
  scgi_temp_path /tmp/scgi_temp;

  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml text/plain application/xml;

  server {
    listen unix:/var/run/cabotage/cabotage.sock;
    root /usr/share/nginx/html;
    index index.html;

    location = /_health/ {
      add_header Content-Type text/plain;
      return 200 'OK';
    }

    error_page 404 /404.html;

    location / {
      try_files $uri $uri/ =404;
    }
  }
}
